### PR TITLE
[FIX #23] Added new twitter widget using twitter post fetcher

### LINKED ISSUE #23: Fixing the vacant space around twitter widget
Current implementation of the twitter widget leaves unnecessary space to the left and right also it doesn't go with the theme. A solution is required by going through this comment on the original issue -> [Here](https://github.com/pythonindia/inpycon2017/issues/18#issuecomment-313901135)

### PR DESCRIPTION
**Pull request by SaptakS**

### CODE REVIEW

**Comment by SaptakS** [comment]
@CuriousLearner @sayanchowdhury @realslimshanky please review. Fixed indentation changes in #66

**Review by CuriousLearner — APPROVED** [review]
Looks good to me.

Will wait for Sayan's review and then merge this in!

**Review by realslimshanky — APPROVED** [review]
LGTM

**Comment by amitsin6h** [comment]
@sayanchowdhury Please review it

**Comment by sayanchowdhury** [comment]
Looks good to me. @amitsin6h you need to rebase though

**Comment by amitsin6h** [comment]
#108 Please review it. Close this PR

**Comment by realslimshanky** [comment]
@SaptakS Please resolve conflict in your PR.

**Comment by amitsin6h** [comment]
@SaptakS delete this pr Twitter tweet has been merged from my PR

**Pull request closed without merging**
