### PR TITLE
[FIX #37] Sponser typo in index

### LINKED ISSUE #37: spelling mistake
I think the spelling of `sponser` should be `sponsor` instead of `sponser`. 

Reference: https://github.com/pythonindia/inpycon2017/blob/master/index.html#L2477

### PR DESCRIPTION
**Pull request by aakashbajaj**
Sponser typo corrected in templates/sections/_sponsors.html

### CODE REVIEW

**Comment by CuriousLearner** [comment]
No need to close PRs like #40  .

Please run a build on the changes and also include the HTML files in this PR>

**Comment by aakashbajaj** [comment]
Got confused before

**Comment by CuriousLearner** [comment]
You've deleted the branch on your fork. Please fix it.

**Comment by aakashbajaj** [comment]
new pull request created due to repo issues.
please refer to pull request #48

**Pull request closed without merging**
