### PR TITLE
Fix sponsor typo everywhere

### PR DESCRIPTION
**Pull request by dhwanilvyas**

### CODE REVIEW

**Comment by SaptakS** [comment]
@dhwanilvyas please avoid making a separate PR altogether. You can comment on the already open PR for the related issue about what you feel should be done and your views rather than creating an entirely new PR. This causes overlapping works.

**Comment by dhwanilvyas** [comment]
Will keep that in mind. Missed the already opened PR. Have commented there for the changes required. Will close this PR once #48 is merged.

**Comment by CuriousLearner** [comment]
Hey @dhwanilvyas ,

Now that #48 is merged in.

Can you please rebase your patch and we can get this merged in?

**Comment by CuriousLearner** [comment]
@SaptakS Review?

**Comment by SaptakS** [comment]
@dhwanilvyas Your PR includes commits by others. That shouldn't happen. Please recheck while rebasing. Something is wrong.

**Comment by dhwanilvyas** [comment]
I suppose @Xizt and @aakash2007 made changes to my PR directly and created a commit.

**Comment by CuriousLearner** [comment]
@rajataaron Let's finalize this one.

**Comment by rajataaron** [comment]
@CuriousLearner ya looks all good to me merge this and close the rest opened PR.

**Pull request merged**
