### PR TITLE
[FIX #37]Corrected Typo in Sponsor

### LINKED ISSUE #37: spelling mistake
I think the spelling of `sponser` should be `sponsor` instead of `sponser`. 

Reference: https://github.com/pythonindia/inpycon2017/blob/master/index.html#L2477

### PR DESCRIPTION
**Pull request by aakashbajaj**

### CODE REVIEW

**Comment by SaptakS** [comment]
@aakash2007 please avoid opening same PRs again and again and closing previous PRs. Try fixing the PR rather than closing it and opening a new PR.

**Comment by SaptakS** [comment]
@CuriousLearner I think this can be merged. LGTM.

**Comment by aakashbajaj** [comment]
Yeah sure

**Review by SaptakS — APPROVED** [review]

**Comment by dhwanilvyas** [comment]
@aakash2007 there are a lot of places where there is a typo in sponsor. You can have a look at my PR here #57 and make the changes accordingly. Missed your PR completely so made the changes and opened a new one.

**Review by CuriousLearner — APPROVED** [review]
Thanks, @aakash2007 for your contributions, @SaptakS for the review.

LGTM.

@dhwanilvyas You can handle the rest changes in your PR. The changes in this PR are public facing, so I'm merging that in. The changes in your PR covers the typo in comments and elsewhere which are essentially code-base changes.

**Pull request merged**
