### PR TITLE
Change talk description's CSS class

### PR DESCRIPTION
**Pull request by priyankt68**
In this PR, a change is made to talk description's div from ```tg-description``` to ```tg-talk-description```. This avoids previously defined ```tg-description``` conflict.

### CODE REVIEW

**Comment by CuriousLearner** [comment]
@priyankt68 for the schedule, once I click on a talk to open up description, it opens up for a second and then again closes.

**Review by realslimshanky — APPROVED** [review]
LGTM

**Comment by realslimshanky** [comment]
@CuriousLearner I do not seem to have this problem. The situation you described happened when I double clicked on the schedule.

**Comment by priyankt68** [comment]
@CuriousLearner I will check once and get back. I did not face this issue when I tested though.

**Comment by CuriousLearner** [comment]
I tested this on Ubuntu 16.10 using Firefox 56. I also tested on Chrome (don't remember the version now) but I had similar experience on both browsers.

**Comment by CuriousLearner** [comment]
I am able to reproduce this on MacOS too. I tested this on chrome and the toggle event fires twice. (I think that is something related to event bubbling, but then I'm not sure.). I have proposed a patch to unbind the click event with the class since there are a lot of nodes having that event.

Refer to: https://github.com/pythonindia/inpycon2017/pull/143

**Comment by CuriousLearner** [comment]
I am closing this. Issue has been resolved with #143

**Pull request closed without merging**
