### PR TITLE
[Enhancement] Popup action added to all Sponsors

### PR DESCRIPTION
**Pull request by vipulgupta2048**
:hatching_chick:  As uniformity should be maintained. Pop-up action has now been added to all five sponsors. More can be easily added, if any new sponsor is announced.  

Please review all the popups, I have included a margin attribute in each image tag because each image was of different dimensions and text wasn't adjusting according to it.

### CODE REVIEW

**Review by CuriousLearner — COMMENTED** [review]
Why are we repeating code for each sponsor?

Can we follow a more DRY approach here?

**Comment by thisisayush** [comment]
@CuriousLearner There are two possible methods for what you are asking:
- Creating a JS function to fetch the data from JSON File and then loading data into modal when sponsor is clicked. (This will require the sponsor section to be generated by JS instead of StaticJinja on client side)
- Second, Customising build.py and parsing ```sponsors.json``` file, passing it to the context and using a loop in template file (```_sponsors.html```) to automatically build the code (this will contain the same work done by @vipulgupta2048 but will be automated if any sponsor is added or removed)

First approach will be more DRY but will result in an additional request and client side rendering while second approach will generate more lines of code for ```index.html```

We can go by any of the two above or a better approach if someone suggests :)

**Comment by realslimshanky** [comment]
@thisisayush in my opinion the first approach will be a better option and it'll not make request everytime you display the modal. Simply store the data of sponsors in a json object variable inside main.js or inside a `.json` file inside `data/api/`. Would like to hear what @CuriousLearner recommends.

**Comment by thisisayush** [comment]
@realslimshanky I'll agree on that. But this will result in rewriting of _sponsors.html. We are good to go if it's fine @CuriousLearner

**Comment by realslimshanky** [comment]
@thisisayush any progress?

**Comment by realslimshanky** [comment]
@vipulgupta2048 please resolve conflicts.

**Comment by vipulgupta2048** [comment]
Done. Ready to merge.

**Comment by realslimshanky** [comment]
@vipulgupta2048 please add writeup + popup for Tensorflow as well.
Use writeup from https://github.com/pythonindia/inpycon-blog/pull/102

**Comment by vipulgupta2048** [comment]
Made the changes as requested.

**Comment by realslimshanky** [comment]
image
Please increase the size of the logo of Tensorflow as much as VisibleAlpha and reduce size of the VisibleAlpha as Tensorflow currently.

**Comment by vipulgupta2048** [comment]
@realslimshanky  Sure. On it.
Also should I center align Visible Alpha with respect to Gold Sponsors ?

**Comment by realslimshanky** [comment]
@vipulgupta2048 yes, please do.

**Comment by akshayaurora** [comment]
> Also should I center align Visible Alpha with respect to Gold Sponsors ?

**Comment by vipulgupta2048** [comment]
@akshayaurora LOL. Last time I made changes to the code for some purpose/action and it lead to a pretty bad mess-up. I just think its better to ask the person maintaining the code whether a part I want to fix is a actually a bug or a feature however obvious it is. I just don't want to break anything.  
@realslimshanky This is how it looks at 100% zoom. Also tested it on some levels for mobile viewing. 

screenshot_2017-10-26_00-38-44

**Comment by realslimshanky** [comment]
Thanks for you contribution @vipulgupta2048 :pizza:

**Pull request merged**
