### PR TITLE
add popup for ZeOmega with description, logo and website link

### PR DESCRIPTION
**Pull request by chirag200666**
Fixes issue: https://github.com/pythonindia/inpycon2017/issues/114

### CODE REVIEW

**Comment by chirag200666** [comment]
@realslimshanky @CuriousLearner @stellargo 
please have a look at this commit. 
Thanks

**Comment by realslimshanky** [comment]
@chirag200666 we can do this for all the sponsors if we want to.

**Comment by chirag200666** [comment]
@realslimshanky 
Yes if we have the write-ups we can.
Anand shared only one description.

**Comment by realslimshanky** [comment]
@rajataaron could you please help @chirag200666 with the write-ups for the sponsors?

**Pull request merged**
