### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by dhruvdutt**
Fixes `Sponsor` and `sponsor` typo/s everywhere.

### CODE REVIEW

**Comment by dhruvdutt** [comment]
@SaptakS @CuriousLearner Please review.

**Comment by sayanchowdhury** [comment]
Wow, you have sharp eyes. Good to merge from me :cookie:

**Comment by SaptakS** [comment]
@sayanchowdhury @dhruvdutt a [similar PR](https://github.com/pythonindia/inpycon2017/pull/57) already exists though. But since that PR has been inactive, I think it's good to merge. @CuriousLearner ??

**Comment by CuriousLearner** [comment]
Resolved by #57

**Pull request closed without merging**
