### PR TITLE
FAQ Working

### PR DESCRIPTION
**Pull request by vsnehil92**

### CODE REVIEW

**Review by CuriousLearner — APPROVED** [review]
This would work. But need to confirm from @priyankt68 why was this added.

**Comment by CuriousLearner** [comment]
We need to check that it shouldn't break any change that was done in the schedule by @priyankt68

**Comment by priyankt68** [comment]
If we comment ```display:none``` in ```.tg-description```, talk descriptions will be displayed by default on page load. Currently on-click event, we toggle CSS of talk description to display it.

@vsnehil92 @CuriousLearner  I am curious why this is needed ? I don't follow completely.

**Comment by vsnehil92** [comment]
In FAQ section the answers are not being displayed because of `display:none` in `.tg-description` @priyankt68

**Comment by priyankt68** [comment]
@vsnehil92  Okay. I should have checked that there exist's a class - ```tg-description``` and therefore should have used a different class name for talk description. My bad. Perhaps, ```tg-talk-description``` would have been apt.

I will make changes immediately to it so that schedule does not break and then we can merge this and my PR post review.

@CuriousLearner @vsnehil92  Will keep you guys posted.

Thanks.

**Comment by priyankt68** [comment]
@CuriousLearner Please check.

https://github.com/pythonindia/inpycon2017/pull/142

**Comment by CuriousLearner** [comment]
Okay, we'll go ahead with @priyankt68 's PR, since that would solve the issue.

**Comment by CuriousLearner** [comment]
I am closing this. Issue has been resolved with #143

**Pull request closed without merging**
