### PR TITLE
[FIX #37] Fixed spelling mistake

### LINKED ISSUE #37: spelling mistake
I think the spelling of `sponser` should be `sponsor` instead of `sponser`. 

Reference: https://github.com/pythonindia/inpycon2017/blob/master/index.html#L2477

### PR DESCRIPTION
**Pull request by amitsin6h**
Fixed sponser typo from the index.html page. This is issue can be closed now.

### CODE REVIEW

**Comment by aakashbajaj** [comment]
The changes need to be done in the templates and then build to render new html files.

**Comment by realslimshanky** [comment]
@amitsin6h you're trying to solve multiple issues with one PR. This makes moderator's job very difficult. Try to pick one issue at a time and after it's fixed with a merged PR try another one. Also, you are not following the guidelines stated in [README.md](https://github.com/pythonindia/inpycon2017/blob/master/README.md)

**Comment by amitsin6h** [comment]
@realslimshanky sorry for that. wont make another PR until my current PR are merged

**Comment by realslimshanky** [comment]
@CuriousLearner we should close this one.

**Comment by SaptakS** [comment]
@amitsin6h either include only the spelling mistake commit, or we are closing this PR.

**Comment by CuriousLearner** [comment]
I'm closing this PR because of this not being an atomic change. Moreover, this was already solved in #48  and a part of it is awaiting changes in #57.

@amitsin6h Thanks for your contributions, but this PR does  too many changes that are not necessary. So, we won't be able to merge this in.

Please look at other issues, and solve only one issue in one PR as others are working on other issues.

Thanks again!

**Pull request closed without merging**
