### PR TITLE
Parallax images added according to theme fixed

### LINKED ISSUE #78: Add parallax image according to theme
Need to add parallax image according to theme finalized.

### PR DESCRIPTION
**Pull request by rajataaron**
1) parallax image added.
2) And done some changes in gradient.

### CODE REVIEW

**Comment by CuriousLearner** [comment]
@rajataaron Can you please paste the gh-pages link of your fork here?

**Comment by sayanchowdhury** [comment]
Looks good to me :100:

**Comment by rajataaron** [comment]
@CuriousLearner I have not set it up on my gh-pages do you want me to do that?

**Comment by rajataaron** [comment]
here is the link to gh-pages https://rajataaron.github.io/inpycon2017/

**Review by CuriousLearner — APPROVED** [review]
LGTM

**Pull request merged**
