### PR TITLE
[Enchancement] Date and Venue redirected, Fixed error

### PR DESCRIPTION
**Pull request by vipulgupta2048**
- An issue with the templates/section _sponsor.html fixed.
- The **date** now redirects to making a newCalendar entry for the user in Google Calendar. 
- The **venue** now redirects to the map API section of the website.

### CODE REVIEW

**Comment by realslimshanky** [comment]
Could you make the same action as on the text for the icon as well? It'll be better that way.

**Comment by vipulgupta2048** [comment]
That's actually a great idea, I thought of doing it, but since it wasn't there before I thought I shouldn't put it up now. Will implement it.

**Comment by vipulgupta2048** [comment]
Changes Implemented. Do see the same.

**Review by realslimshanky — APPROVED** [review]
LGTM

**Comment by realslimshanky** [comment]
@CuriousLearner would you please look into it. I think it's good to go.

**Comment by akshayaurora** [comment]
@vipulgupta2048 thanks 👍

**Pull request merged**
