### PR TITLE
[Fix 131]Changed mobile-view for schedule

### LINKED ISSUE #131: Alternate solution is required for Date & Hall/Room tabs on the mobile view
An alternate solution is required which should take lesser space for both the situations stated below. Please discuss what your solution might be. I suggest a dropdown menu.
On mobile, the Dates in the schedule section looks something like this on the mobile.
image
And the Hall/Room tab looks like.
image

### PR DESCRIPTION
**Pull request by atb00ker**
Fixes #131 
@realslimshanky 
github

### CODE REVIEW

**Comment by realslimshanky** [comment]
Good work @ATB00ker 
There is one simple issue to take care here. When we select one of the halls or classroom it is not displayed anywhere what we have selected hence it might get confusing, could you please add a simple text which shows which hall or classroom the user has selected anywhere near these
image
texts which, like your feature only works on mobile screens.

**Comment by atb00ker** [comment]
On it! :)

**Comment by atb00ker** [comment]
github

Change made: Hall Name displayed below date! :)

**Comment by CuriousLearner** [comment]
Can you try highlighting the active hall name on mobile view? (Just for better UX)?

**Comment by atb00ker** [comment]
screenshot from 2017-10-19 00-50-34
Change made: Added the desktop page tab style to mobile tab for better UX! :)
@CuriousLearner

**Comment by realslimshanky** [comment]
.@ATB00ker it looks like a button. If we can get rid of the shadowed box it'll be okay.

**Comment by atb00ker** [comment]
github
Change made: Removed Shadow to avoid making it look like a button!
@realslimshanky

**Comment by realslimshanky** [comment]
@ATB00ker looks great. Merging your changes in.

**Comment by realslimshanky** [comment]
@ATB00ker I've been testing a bit deeper as the final pass. I've got a bug I would like you to debug and fix. When you change from one day to another on the mobile view that day's schedule is just appended on the older one which was last visited. Please check why is this happening and fix it.

**Comment by atb00ker** [comment]
I am unable to reproduce the bug. Can you please tell more specific steps to do it?

**Comment by realslimshanky** [comment]
@ATB00ker you can click on 'Day 2 Seminar Hall 1' then 'Day 3 Seminar Hall 2' for example to recreate the bug.

**Comment by atb00ker** [comment]
If looks like the default active class of desktop view was interfering with the mobile view, thanks for informing, i have patched it! :)

**Comment by akshayaurora** [comment]
@ATB00ker thanks

**Pull request merged**
