### PR TITLE
Added twitter widget

### PR DESCRIPTION
**Pull request by amitsin6h**
Added twitter widget @sayanchowdhury @theskumar @CuriousLearner @realslimshanky .
Please review it.

### CODE REVIEW

**Comment by realslimshanky** [comment]
Text crosses the margin of div.
image
Possible fix can be
1) Wrap text inside div using css `word-wrap: break-word;`
or
2) Allow content to be scrolled around using css `overflow-x: scroll`

**Comment by amitsin6h** [comment]
Fixed text margin issue. thanks for suggestion @realslimshanky

**Review by realslimshanky — APPROVED** [review]
LGTM.

**Comment by amitsin6h** [comment]
@akshayaurora

**Comment by realslimshanky** [comment]
@amitsin6h your branch has conflicts with the master, please resolve them first.

**Comment by amitsin6h** [comment]
@realslimshanky @akshayaurora @sayanchowdhury @CuriousLearner @theskumar @SaptakS  guys please review it and merge if everything looks great.

**Comment by amitsin6h** [comment]
Thanks @akshayaurora :+1:

**Pull request merged**
