### PR TITLE
Adding contribute to this page option

### PR DESCRIPTION
**Pull request by storymode7**
screenshot-2017-10-29 pycon india 2017

### CODE REVIEW

**Comment by realslimshanky** [comment]
@storymode7 thanks for the effort to put this on the website brother but the point here is do we need this so close to the conference?
cc: @rajataaron @CuriousLearner

**Comment by storymode7** [comment]
I thought just in case , anyone wants to get started to experiment with this website before or even after pycon , they might find some help.

**Comment by realslimshanky** [comment]
@storymode7 I think it's a great idea too. I'm waiting to see what other's might review. Rest LGTM.

**Review by CuriousLearner — COMMENTED** [review]
Thanks for putting in effort for this PR. We really appreciate that. But, I am not sure if we really need this now; given that the conference is next week.

Having said that, there are changes needed like:

_We don't want to create a whole HTML page. We had to add another template for contribution which would inherit from the base template._

This PR is not yet mergeable. But thank you for your changes.

You could consider doing changes, but again, this close too the conference, I don't think it is worth putting in the effort for this one. 

There are various tasks lying around where you could help & which have a higher priority at this point of time. :)

**Comment by storymode7** [comment]
Thanks for the review :)
I'll surely go for different projects .

**Pull request closed without merging**
